import type { Metadata } from "next";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

import styles from "./layout.module.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "hiro08.dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Header />
        <div className={styles.main}>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
